DTL\Bundle\ContentBundle\Document\HomepageDocument:
    uri_schema: "/"
    conflict_resolver: throw_exception

DTL\Bundle\ContentBundle\Document\PageDocument:
    uri_schema: "{resource_locator}/{title}"
    token_providers:
        resource_locator: [content_method, { method: getResourceLocator, collapse_empty: true, slugify: false  }]
        title: [content_method, { method: getTitle }]
    conflict_resolver: auto_increment
